In [1]:
import json

# Leemos la data
filepath = "graphql"
with open(filepath, "r") as f:
    print(f"Reading {filepath}")
    data = json.load(f)

# La limpiamos y guardamos
if "chat" in data[0]["data"]:
    print("Deleting chat data")
    del data[0]["data"]["chat"]
    with open(filepath, "w") as f:
        json.dump(data, f)

Reading graphql

In [2]:
import pandas as pd

# Generamos DF con los datos
recipes = data[0]["data"]["recipes"]
df = pd.json_normalize(recipes)
df

,id,title,subtitle,description,labelsId,images,nutritionFacts.calories,nutritionFacts.protein,nutritionFacts.fat,nutritionFacts.carbohydrate,preparation.ingredients,preparation.instructions,preparation.prepTime,preparation.cookTime
0,8da264de-3a7b-4036-9ad4-d646a03a962e,Rapiditas con queso y tomate,,,"[mealType-breakfast, mealType-snack, mealType-...",[{'key': 'close-up-woman-holding-up-tasty-taco...,150.0,NaN,NaN,None,"Infusión a elección, 2 rapiditas integrales, q...",Colocar 1 porción de queso y rodajas de tomate...,15.0,None
1,7b9b4715-624b-4194-932c-4304f24f4715,Infusión con tostada con fruta,,,"[mealType-breakfast, mealType-afternoon-snack,...","[{'key': 'pexels-solodsha-8605125.jpg', 'value...",136.0,NaN,NaN,None,"Infusión a elección, 1 pan lactal de salvado s...",Preparar la infusión y tostar el pan. Luego ag...,2.0,None
2,4e58f061-de8e-4c8d-bcc5-3bd95598110a,Ensalada de fideos sin tacc,,,"[mealType-lunch, mealType-dinner, recipeType-r...","[{'key': 'pexels-lisa-fotios-8385550.jpg', 'va...",396.0,NaN,NaN,None,"80g de fideos sin tacc (1 taza), tomates cherr...","Cocinar los fideos. Por otro lado, saltear las...",20.0,None
3,7f01aa1b-3f0c-4887-82c9-c02f20e294ef,Revuelto con vegetales,,,"[userDiet-vegetarian, mealType-lunch, mealType...",[{'key': 'top-view-delicious-vegetable-salad-w...,409.0,NaN,NaN,None,"Zapallitos, morrón, zanahoria, cebolla, choclo...",Saltear los vegetales y cuando esten cocidos a...,20.0,None
4,bc9ef9df-90b8-4d16-8e2b-3ea8e9da6e65,Ensalada de atún y vegetales.,,,"[mealType-lunch, mealType-dinner, recipeType-r...","[{'key': 'tuna-salad.jpg', 'value': 'https://a...",363.0,NaN,NaN,None,"1/2 lata de atún al natural, palmitos, tomate,...",Lavar y cortar los vegetales. Agregarles atún ...,30.0,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
215,c36bcf35-5aaf-405c-a32a-f37c3cc7eff6,"Copa con banana, frutilla, dulce de leche y crema",,,"[userHealth-gluten-free, mealType-breakfast, r...",[{'key': '65b01254-5003-40b6-bf2a-e5eb217ac645...,400.0,NaN,NaN,None,"Media banana, 2 frutillas, 1 cucharada sopera ...",Tomar un vaso grande y hacer cuatro capas:\n- ...,NaN,None
216,0ce02220-5971-42e9-a9f2-b1bbcc1b1a98,Infusión + frutas secas,None,None,"[mealType-breakfast, mealType-afternoon-snack,...",[{'key': 'top-view-of-nuts-concept-with-copy-s...,153.0,NaN,NaN,None,Infusión a elección + 1 puñado de la mano cerr...,Servir la infusión y un puñado de frutas secas,5.0,None
217,2aac6ec4-8cdc-4070-b2d1-c198165e748c,Sándwich con verduras,,,"[userDiet-vegetarian, mealType-lunch, mealType...",[{'key': 'overhead-shot-of-three-delicious-san...,453.0,NaN,NaN,None,Sándwich con pan negro relleno con rodajas de ...,Colocar con ingredientes entre ambos panes. Se...,25.0,None
218,2e263964-257b-4e84-a0db-2a3c3976eeb7,"Ensalada de lentejas, nueces y vegetales",,,"[mealType-lunch, mealType-dinner, recipeType-r...","[{'key': 'lentejas.PNG', 'value': 'https://ass...",590.0,NaN,NaN,None,"5 cdas de lentejas + 1 huevo duro + tomate, rú...",Cocinar las lentejas y dejarlas enfriar. Agreg...,25.0,None
219,0568a3e8-5afb-4461-a4e1-d7997deaf989,Milanesa de carne con ensalada tricolor,,,"[mealType-lunch, mealType-dinner, recipeType-r...","[{'key': 'milanesa.PNG', 'value': 'https://ass...",624.0,NaN,NaN,None,"1 milanesa de carne, 1 rebanada de queso crem...",Cocinar la milanesa en el horno y cuando este ...,40.0,None

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 220 entries, 0 to 219
Data columns (total 14 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   id                           220 non-null    object
 1   title                        220 non-null    object
 2   subtitle                     153 non-null    object
 3   description                  153 non-null    object
 4   labelsId                     220 non-null    object
 5   images                       220 non-null    object
 6   nutritionFacts.calories      213 non-null    float64
 7   nutritionFacts.protein       7 non-null      float64
 8   nutritionFacts.fat           4 non-null      float64
 9   nutritionFacts.carbohydrate  0 non-null      object
 10  preparation.ingredients      220 non-null    object
 11  preparation.instructions     220 non-null    object
 12  preparation.prepTime         204 non-null    float64
 13  preparation.cookTime         0 non-null      object
dtypes: float64(4), object(10)
memory usage: 24.2+ KB

In [4]:
df[df["nutritionFacts.fat"].isnull() == False]

,id,title,subtitle,description,labelsId,images,nutritionFacts.calories,nutritionFacts.protein,nutritionFacts.fat,nutritionFacts.carbohydrate,preparation.ingredients,preparation.instructions,preparation.prepTime,preparation.cookTime
51,145cdac9-9346-4486-ab41-4e8670fb7e80,Infusión con tostadas con mantequilla de maní,,,"[mealType-breakfast, mealType-snack, mealType-...",[{'key': 'pexels-karolina-grabowska-6659689.jp...,137.0,NaN,137.0,None,Infusión a elección + 3 tostadas integrales de...,,5.0,None
70,381fa03a-3b08-444a-aa12-f32a9427c175,Fideos salteados con vegetales,,,"[mealType-lunch, mealType-dinner, recipeType-r...","[{'key': 'pexels-makafood-9045156.jpg', 'value...",403.0,NaN,10.0,None,"Fideos (integrales en lo posible), morrón, zan...","Cortar en tiritas cebolla, morrón (rojo y verd...",20.0,None
116,0b85b15a-ca8b-4327-852d-00ab86b049be,Fideos de legumbres salteados con vegetales si...,,,"[mealType-lunch, mealType-dinner, recipeType-r...",[{'key': 'pexels-polina-tankilevitch-4518703.j...,403.0,NaN,10.0,None,"Fideos de legumbres sin tacc,\n Morrón,\n Zana...","\n \n Cortar en tiritas cebolla, morrón (rojo ...",20.0,None
141,117886a7-3bcb-4da4-92aa-27130f60e50f,Canelones de verdura,None,None,"[userDiet-vegetarian, mealType-lunch, mealType...",[{'key': 'canelones-de-pollo-con-espinacas.jpg...,NaN,20.0,14.0,None,Para 4 unidades:\n 4 panqueques\n 200 gr ricot...,Pasos a seguir:\n En una sartén con un poquito...,30.0,None

In [5]:
df[df["nutritionFacts.protein"].isnull() == False]

,id,title,subtitle,description,labelsId,images,nutritionFacts.calories,nutritionFacts.protein,nutritionFacts.fat,nutritionFacts.carbohydrate,preparation.ingredients,preparation.instructions,preparation.prepTime,preparation.cookTime
15,5bd5ee4f-00b5-46d7-9e66-acf0ef5c8733,Ensalada fría,,,"[mealType-lunch, mealType-dinner, recipeType-r...","[{'key': 'pexels-алекке-блажин-8254667.jpg', '...",459.0,53.0,NaN,None,"Tiritas de carne o pollo, tomate, zanahoria, a...",Cortar tiritas de carne o de pollo y cocinar e...,20.0,None
106,a53fbe94-1d0b-4515-88cd-4a47e55ac597,Infusión + tostado de queso y tomate,,,"[mealType-breakfast, mealType-afternoon-snack,...","[{'key': 'cafe_tostado.jpg', 'value': 'https:/...",188.0,10.1,NaN,None,"Queso cremoso light, pan lactal integral, toma...",Infusión a elección con 1 tostado (con 2 reban...,1.0,None
120,c95c5ef4-4d16-447d-b54b-bcea40252178,Fruta,,,"[userDiet-vegetarian, mealType-breakfast, meal...","[{'key': 'pexels-suzy-hazelwood-1510392.jpg', ...",78.0,1.0,NaN,None,Una fruta,,1.0,None
122,0a4190d3-bb2a-4ea3-a762-4a11a8558166,Yogurt vegano,,,"[mealType-breakfast, mealType-afternoon-snack,...",[{'key': 'pexels-anastasia-belousova-8892362.j...,80.0,8.0,NaN,None,1 yogurt vegano (firme o bebible),,1.0,None
126,dec2d759-2d0d-4ac0-81c4-567c36353513,Yogurt con granola sin tacc,,,"[mealType-breakfast, mealType-afternoon-snack,...",[{'key': 'front-view-of-glasses-with-yogurt-an...,1.0,188.0,NaN,None,"1 yogurt descremado, granola sin tacc",Añadir 30 gr de granola sin tacc (un puñado) a...,NaN,None
141,117886a7-3bcb-4da4-92aa-27130f60e50f,Canelones de verdura,None,None,"[userDiet-vegetarian, mealType-lunch, mealType...",[{'key': 'canelones-de-pollo-con-espinacas.jpg...,NaN,20.0,14.0,None,Para 4 unidades:\n 4 panqueques\n 200 gr ricot...,Pasos a seguir:\n En una sartén con un poquito...,30.0,None
169,fdb8812e-b05d-4a1f-8076-75c8d8303189,Morrones rellenos de carne,None,None,"[mealType-lunch, mealType-dinner, recipeType-r...",[{'key': 'top-close-view-delicious-vegetable-d...,NaN,495.0,NaN,None,"2 morrones, carne picada magra, cebolla, morró...",Cocinar la carne picada junto con los vegetale...,25.0,None

In [6]:
df["subtitle"].value_counts()

subtitle
    153
Name: count, dtype: int64

In [7]:
df["description"].value_counts()

description
    153
Name: count, dtype: int64

In [13]:
df_filtered = (
    df[["title", "labelsId", "images", "nutritionFacts.calories", "preparation.ingredients", "preparation.instructions", "preparation.prepTime"]]
    .rename(lambda col: col.split(".")[-1], axis=1)
)
df_filtered

,title,labelsId,images,calories,ingredients,instructions,prepTime
0,Rapiditas con queso y tomate,"[mealType-breakfast, mealType-snack, mealType-...",[{'key': 'close-up-woman-holding-up-tasty-taco...,150.0,"Infusión a elección, 2 rapiditas integrales, q...",Colocar 1 porción de queso y rodajas de tomate...,15.0
1,Infusión con tostada con fruta,"[mealType-breakfast, mealType-afternoon-snack,...","[{'key': 'pexels-solodsha-8605125.jpg', 'value...",136.0,"Infusión a elección, 1 pan lactal de salvado s...",Preparar la infusión y tostar el pan. Luego ag...,2.0
2,Ensalada de fideos sin tacc,"[mealType-lunch, mealType-dinner, recipeType-r...","[{'key': 'pexels-lisa-fotios-8385550.jpg', 'va...",396.0,"80g de fideos sin tacc (1 taza), tomates cherr...","Cocinar los fideos. Por otro lado, saltear las...",20.0
3,Revuelto con vegetales,"[userDiet-vegetarian, mealType-lunch, mealType...",[{'key': 'top-view-delicious-vegetable-salad-w...,409.0,"Zapallitos, morrón, zanahoria, cebolla, choclo...",Saltear los vegetales y cuando esten cocidos a...,20.0
4,Ensalada de atún y vegetales.,"[mealType-lunch, mealType-dinner, recipeType-r...","[{'key': 'tuna-salad.jpg', 'value': 'https://a...",363.0,"1/2 lata de atún al natural, palmitos, tomate,...",Lavar y cortar los vegetales. Agregarles atún ...,30.0
...,...,...,...,...,...,...,...
215,"Copa con banana, frutilla, dulce de leche y crema","[userHealth-gluten-free, mealType-breakfast, r...",[{'key': '65b01254-5003-40b6-bf2a-e5eb217ac645...,400.0,"Media banana, 2 frutillas, 1 cucharada sopera ...",Tomar un vaso grande y hacer cuatro capas:\n- ...,NaN
216,Infusión + frutas secas,"[mealType-breakfast, mealType-afternoon-snack,...",[{'key': 'top-view-of-nuts-concept-with-copy-s...,153.0,Infusión a elección + 1 puñado de la mano cerr...,Servir la infusión y un puñado de frutas secas,5.0
217,Sándwich con verduras,"[userDiet-vegetarian, mealType-lunch, mealType...",[{'key': 'overhead-shot-of-three-delicious-san...,453.0,Sándwich con pan negro relleno con rodajas de ...,Colocar con ingredientes entre ambos panes. Se...,25.0
218,"Ensalada de lentejas, nueces y vegetales","[mealType-lunch, mealType-dinner, recipeType-r...","[{'key': 'lentejas.PNG', 'value': 'https://ass...",590.0,"5 cdas de lentejas + 1 huevo duro + tomate, rú...",Cocinar las lentejas y dejarlas enfriar. Agreg...,25.0
219,Milanesa de carne con ensalada tricolor,"[mealType-lunch, mealType-dinner, recipeType-r...","[{'key': 'milanesa.PNG', 'value': 'https://ass...",624.0,"1 milanesa de carne, 1 rebanada de queso crem...",Cocinar la milanesa en el horno y cuando este ...,40.0

In [14]:
df_sorted = df_filtered.sort_values("calories", ascending=False)
df_sorted

,title,labelsId,images,calories,ingredients,instructions,prepTime
17,Tarta de verdura (3 porciones),"[mealType-lunch, mealType-dinner, recipeType-r...",[{'key': 'close-up-photo-of-baked-tart-dough-w...,650.0,"Espinaca o acelga, cebolla, morrón, zanahoria ...",Lavar y cocinar las verduras. \nColocar el rel...,30.0
56,Ensalada de pollo completa,"[mealType-lunch, mealType-dinner, recipeType-f...","[{'key': 'pexels-fillvlad-10273499.jpg', 'valu...",650.0,"Ensalada con: 1 pechuga chica, lechuga, tomate...","Lavar los vegetales, cortarlos y mezclarlos co...",30.0
64,Tarta de verdura sin tacc (3 porciones),"[mealType-lunch, mealType-dinner, recipeType-r...",[{'key': '5eab3fb6-ded4-437f-974f-e368b7928572...,650.0,"Espinaca o acelga, cebolla, morrón, zanahoria ...",Lavar y cocinar las verduras. \nColocar el rel...,30.0
21,Tarta casera de champignones (3 porciones),"[mealType-lunch, mealType-dinner, recipeType-r...",[{'key': '5eab3fb6-ded4-437f-974f-e368b7928572...,650.0,Para la masa necesitas:\n 250g harina integral...,Paso a paso (Masa) \n En un bowl ponemos la ha...,40.0
131,Tarta de zucchini y calabaza (3 porciones,"[mealType-lunch, mealType-dinner, recipeType-r...","[{'key': 'tarta-salada-calabaza-receta.jpg', '...",650.0,"2 tapas de tarta, semillas cebolla, zucchinis,...",Salteá con apenas de aceite una cebolla cortad...,40.0
...,...,...,...,...,...,...,...
124,Budín de zanahoria y nueces,"[mealType-breakfast, mealType-afternoon-snack,...","[{'key': 'Captura de pantalla (159).png', 'val...",NaN,Budín de zanahoria y nueces\n\n 3/4 taza de ha...,Paso a paso:\n1.Colocar todos los ingredientes...,NaN
128,Chocotorta,"[mealType-dessert, mealType-afternoon-snack, r...",[{'key': '77509-la-chocotorta-fue-elegida-como...,NaN,"500g de dulce de leche repostero, 500g de Casa...",El procedimiento es simple: Capa de relleno (d...,NaN
141,Canelones de verdura,"[userDiet-vegetarian, mealType-lunch, mealType...",[{'key': 'canelones-de-pollo-con-espinacas.jpg...,NaN,Para 4 unidades:\n 4 panqueques\n 200 gr ricot...,Pasos a seguir:\n En una sartén con un poquito...,30.0
169,Morrones rellenos de carne,"[mealType-lunch, mealType-dinner, recipeType-r...",[{'key': 'top-close-view-delicious-vegetable-d...,NaN,"2 morrones, carne picada magra, cebolla, morró...",Cocinar la carne picada junto con los vegetale...,25.0
171,Berenjenas rellenas con ensalada,"[mealType-lunch, mealType-dinner, recipeType-r...","[{'key': 'baked-aubergines-boats.jpg', 'value'...",NaN,"2 berenjenas rellenas de carne picada, arvejas...",Cortar las berenjenas y coloarlas en el horno ...,35.0

In [15]:
with open("recipes.json", "w") as f:
    df_sorted.to_json(f, orient="records")